// --- The navigation between pages ---
//
// Two parts. The first part takes a click on a link of the note body and
// decides where it goes. The second part shows the progress overlay when
// the next page is slow.
//
// index.html loads this file after omn-go-core.js, because the second part
// uses window.OMNProgress. Each part does its work in a DOMContentLoaded
// listener.

// Intercept Markdown links for standard browser-side redirects
function setupPreviewLinkInterceptor() {
    var preview = document.getElementById('preview');
    if (!preview) return;
    preview.addEventListener('click', (e) => {
    let target = e.target.closest('a');
    if(target) {
        const href = target.getAttribute('href');
        if (href) {
            // Pure anchors and javascript: actions - leave the
            // browser's native handling completely alone.
            if (href.startsWith('#') || href.startsWith('javascript:')) {
                return;
            }

            // http(s):// and protocol-relative "//" links are
            // external - open them in a new tab instead of
            // navigating the app itself away.
            if (/^https?:\/\//i.test(href) || href.startsWith('//')) {
                e.preventDefault();
                window.open(href, '_blank');
                return;
            }

            // Any other URI scheme (tel:, mailto:, geo:, sms:,
            // market:, intent://, whatsapp:, ...) is not a page
            // reference at all. Leave it untouched, and the link
            // handling of the browser or the WebView launches the
            // matching app. This used to fall through to the
            // "internal page" rewrite below. That rewrite appended
            // a bogus ".html" onto anything with no literal "." in
            // it, thus "tel:5551234" became "tel:5551234.html" and
            // stopped working.
            if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(href)) {
                return;
            }

            // Everything else is an internal page reference. The server
            // already normalized this exact href when it rendered the
            // page. render.Renderer.RewriteInternalLink in
            // internal/render/markdown.go converts ".md" to ".html". It
            // appends ".html" to a bare page name, and it leaves a
            // "?query" or a "#fragment" suffix untouched. Nothing is
            // left to redo here. The old naive re-check below used to
            // re-break a correct href. "Page?x=1" became
            // "Page?x=1.html", and "Page.md#section" kept a literal
            // ".md" that gives 404, because it matched neither of the
            // two branches. Navigate to exactly what the server
            // rendered.
            e.preventDefault();
            window.location.href = href;
        }
    }
});
}
document.addEventListener('DOMContentLoaded', setupPreviewLinkInterceptor);

// --- Slow-navigation guard ---
//
// Some pages are generated by the server AT NAVIGATION TIME. The wait then
// happens after the browser has left this document, and no in-page spinner can
// cover it. OMNGoTags rebuilds when it scans every note, see
// internal/render/tags.go. A note whose .md is newer than its cached .html is
// recompiled on the first view, see serveHTMLPage. That is every changed note
// after a pull.
//
// Nothing here can shorten that wait. It can stop the UI from looking dead
// while the wait happens. On a link click we arm a short timer. The overlay
// comes up only when the new document has not taken over by then, thus a
// quick navigation never flashes. The overlay dies with the document, thus
// there is nothing to clean up on the way out.
//
// On Android the native ProgressBar in WebViewSetup covers the same gap
// (onPageStarted/onPageFinished) including back/forward and direct URL
// loads, which a click handler cannot see. This is the desktop counterpart.
document.addEventListener("DOMContentLoaded", () => {
    // Exported pages opened from disk have no server and no generated pages.
    if (window.location.protocol === 'file:') return;

    const DELAY_MS = 300;
    let timer = null;

    document.addEventListener('click', function(ev) {
        if (ev.defaultPrevented || ev.button !== 0) return;
        if (ev.metaKey || ev.ctrlKey || ev.shiftKey || ev.altKey) return;
        const a = ev.target && ev.target.closest ? ev.target.closest('a') : null;
        if (!a || !a.href) return;
        // New tab/window and downloads leave this document in place.
        if (a.target && a.target !== '_self') return;
        if (a.hasAttribute('download')) return;

        let url;
        try { url = new URL(a.href, window.location.href); } catch (e) { return; }
        // Skip cross-origin and non-http schemes (mailto:, intent:, ...).
        if (url.origin !== window.location.origin) return;
        if (url.protocol !== 'http:' && url.protocol !== 'https:') return;
        // A bare in-page anchor (including the Config sub-screen hashes)
        // changes no document and must not raise an overlay.
        if (url.pathname === window.location.pathname &&
            url.search === window.location.search) return;

        clearTimeout(timer);
        timer = setTimeout(function() {
            window.OMNProgress.show('Loading');
            window.OMNProgress.stage('Preparing page…');
            // decodeURIComponent can throw on a malformed %-sequence.
            let where = url.pathname;
            try { where = decodeURIComponent(url.pathname); } catch (e) {}
            window.OMNProgress.detail(where);
        }, DELAY_MS);
    }, true);

    // The form of the results page is a navigation too, and the wait behind
    // it is the largest one that this guard covers. A submit of the query
    // reads every note that the index holds, and the server renders the
    // answer. The click handler above cannot see it, because a submit is
    // not an <a>.
    //
    // NO debounce here, unlike the search dialog. A submit IS the "go" that
    // the dialog has to wait for a typist to mean. The DELAY_MS below is not
    // a delay before the search. The request is already on its way while
    // DELAY_MS runs. It is the same anti-flash arming that the click handler
    // uses, thus a fast answer arrives and no overlay appears at all.
    //
    // Matched by class rather than by "any GET form". A note may contain a
    // form of its own, because raw HTML is allowed, see ScriptRules. The
    // word "Searching" would be a lie over the form of someone else. This
    // is the one form that the app ships and that navigates.
    // search_page.html and the .search-page-* rules in omn-go-core.css
    // already name it the same way.
    //
    // Bubble phase, not capture, so a handler that cancels the submit has
    // already run and set defaultPrevented.
    document.addEventListener('submit', function(ev) {
        if (ev.defaultPrevented) return;
        const form = ev.target;
        if (!form || !form.classList || !form.classList.contains('search-page-form')) return;

        clearTimeout(timer);
        timer = setTimeout(function() {
            window.OMNProgress.show('Searching');
            window.OMNProgress.stage('Reading your notes…');
        }, DELAY_MS);
    });

    // Same-document hash navigation (Config sub-screens) must never leave a
    // pending timer armed behind it.
    window.addEventListener('hashchange', () => clearTimeout(timer));
});
